name: final_job
on: 
  workflow_dispatch:
    inputs:
      skipFinalJob:
        description: 'Set to true to skip the final job'
        required: false
        default: false
        type: boolean
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1-step1
        shell: pwsh
        run: Write-Verbose -Message "OK" -Verbose
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: job2-step1
        shell: pwsh
        run: |
          throw "Fail"
  final-job:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: ${{ always() && ! inputs.skipFinalJob }}
    steps:
      - name: Consume step output
        shell: pwsh
        run: |
          Write-Verbose -Message "Final Job" -Verbose
