name: githubapi
on: 
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Push to branch via git cli
        shell: bash
        run: |
          targetBranch=verified
          git push origin HEAD:$targetBranch --force   
      - name: Create tag via github-script
        uses: actions/github-script@v7
        env:
          GITHUB_SHA: ${{ env.GITHUB_SHA }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { GITHUB_SHA } = process.env
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/v-${GITHUB_SHA}`,
              sha: context.sha
            })
