name: in_out_jobs
on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      JOB1_A: ${{ steps.job1-step1.outputs.step1_output_a }}
    steps:
      - name: job1-step1
        id: job1-step1
        working-directory: .
        shell: pwsh
        run: |
          Get-Item -Path $env:GITHUB_OUTPUT
          "step1_output_a=yellow" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Consume step output
        shell: pwsh
        env:
          OUTPUT_A: ${{ needs.job1.outputs.JOB1_A }}
        run: |
          Write-Verbose -Message "Inline: ${{ needs.job1.outputs.JOB1_A }}" -Verbose
          Write-Verbose -Message "As ENV: ${env:OUTPUT_A}" -Verbose
