name: scheduled-values

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  deploy-nonprod-primary:
    uses: ./.github/workflows/matrix_manyenvs.yaml
    with:
      envFilter: non-prod
      mode: complete
  
  deploy-nonprod-secondary:
    uses: ./.github/workflows/matrix_manyenvs.yaml
    with:
      envFilter: non-prod-dr
      mode: minimal
