name: scriptexec_var
on: 
  workflow_dispatch:

env:
  IN_ACTOR_NAME: BobTheVar

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: job1-step1
        working-directory: .
        shell: pwsh
        run: |
          & .\scripts\Test-Script.ps1 -Name "$env:IN_ACTOR_NAME" -ErrorAction Stop -Verbose
          