name: scriptexec
on: 
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: job1-step1
        working-directory: .
        shell: pwsh
        run: |
          & .\scripts\Test-Script.ps1 -Name "Bob" -ErrorAction Stop -Verbose
