name: secrets_vars_envs
on: 
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: job1-step1
        working-directory: .
        env:
          TEST_SECRET1: ${{ secrets.TEST_SECRET1 }}
          REPO_SECRET1: ${{ secrets.REPO_SECRET1 }}
          TEST_VAR1: ${{ vars.TEST_VAR1 }}
          REPO_VAR1: ${{ vars.REPO_VAR1 }}
        run: |
          echo Environment secret: $TEST_SECRET1
          echo Repo secret: $REPO_SECRET1
          echo Environment variable: $TEST_VAR1
          echo Repo variable: $REPO_VAR1
          echo 'Inline Repo variable: ${{ vars.REPO_VAR1 }}'
          